name: Build and Test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop
      - release/*
      - feature/*

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  install-dependencies:
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/cache/restore@v4
        id: yarn-cache-restore
        with:
          path: |
            ${{ vars.DEPENDENCIES_CACHE_DIR }}
            ${{ vars.UNPLUGGED_CACHE_DIR }}
            ${{ vars.INSTALL_STATE_PATH }}
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: ./.github/actions/setup-node
        with:
          node-version-file: '.nvmrc'

      - uses: ./.github/actions/setup-package-manager

      - name: Install dependencies with cache
        if: steps.yarn-cache-restore.outputs.cache-hit == 'true'
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Install dependencies without cache
        if: steps.yarn-cache-restore.outputs.cache-hit != 'true'
        run: yarn install --immutable --check-cache

      - name: Save dependencies cache
        uses: actions/cache/save@v4
        id: yarn-cache-save
        with:
          path: |
            ${{ vars.DEPENDENCIES_CACHE_DIR }}
            ${{ vars.UNPLUGGED_CACHE_DIR }}
            ${{ vars.INSTALL_STATE_PATH }}
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ${{ vars.DEPENDENCIES_CACHE_DIR }}
            ${{ vars.UNPLUGGED_CACHE_DIR }}
            ${{ vars.INSTALL_STATE_PATH }}
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: ./.github/actions/setup-node
        with:
          node-version-file: '.nvmrc'

      - uses: ./.github/actions/setup-package-manager

      - name: Build Affected Apps
        run: yarn nx affected -t build --base=origin/${GITHUB_BASE_REF} --head=origin/${GITHUB_HEAD_REF}

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ${{ vars.DEPENDENCIES_CACHE_DIR }}
            ${{ vars.UNPLUGGED_CACHE_DIR }}
            ${{ vars.INSTALL_STATE_PATH }}
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: ./.github/actions/setup-node
        with:
          node-version-file: '.nvmrc'

      - uses: ./.github/actions/setup-package-manager

      - name: Test
        run: yarn nx affected -t test --base=origin/${GITHUB_BASE_REF} --head=origin/${GITHUB_HEAD_REF}
