name: Make Subject Branch

on:
  create:
    branches:
      - 'feature/test-only.*'

jobs:
  clean-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Remove Implementation Files
        run: ./scripts/shell/clean_implementation_files.sh

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"

          git reset --soft HEAD^
          git add .
          git commit -m "테스트 앱을 위한 구현체 삭제"
          git push --force
