name: Build and Test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop
      - release/*
      - feature/*

jobs:
  setup:
    name: Setup
    if: github.repository == 'pmmm114/FE_Subject'
    uses: ./.github/workflows/resuable_setup.yml
  build_and_test:
    needs: setup
    name: Build and Test
    uses: ./.github/workflows/resuable_build_and_test.yml
    with:
      build: true
      test: true
      exclude_affected_type: 'app'
